#!/bin/bash

python3 -m venv sugar-env
source sugar-env/bin/activate

pip install --upgrade pip
pip install -r sugar/requirements.txt
pip install service_identity --force --upgrade
pip install git+https://github.com/rtfd/recommonmark.git

cd sugar
SITE_PACKAGES="$(python -c "import sysconfig;print(sysconfig.get_paths()['purelib'])")"
ln -s $(pwd) $SITE_PACKAGES
