#!/bin/bash
#
# Author: Bo Maryniuk <bo@maryniuk.net>

PY_EXE="python3"
MY_HME="$(pwd)"

#
# Checkout repo
#
function checkout_repo () {
    git clone git@github.com:sugarsack/sugar.git
}

#
# Create virtual environment
#
function setup_virt_env () {
    python3 -m venv sugar-env

    source sugar-env/bin/activate

    pip install --upgrade pip
    pip install -r sugar/requirements.txt
    pip install service_identity --force --upgrade
    pip install git+https://github.com/rtfd/recommonmark.git

    cd sugar

    # Link it to the virtual environment instead of installing
    # This will allow to use it and break too :-) during the development.
    ln -s "$(pwd)/sugar" "$(python -c "import sysconfig;print(sysconfig.get_paths()['purelib'])")"
}

#
# Check python version. Minimun 3.5 is required
#
function check_python_version () {
    if ! hash $PY_EXE; then
	echo "Python 3 executable is not found, using default"
	PY_EXE="python"
	if ! hash $PY_EXE; then
	    echo "No Python found, exiting..."
	    exit 1
	fi
    fi
    echo "Using your $(which $PY_EXE) for setup"
}

#
# Check if openssl is around
#
function check_openssl_installed () {
    if ! hash openssl; then
	echo "Please install openssl tools to continue"
	exit 1;
    fi
}

#
# Create ~/.sugar configuration symlink
#
function setup_configuration_symlink () {
    cd $MY_HME
    ln -s $(pwd)/sugar/etc/sugar $HOME/.sugar
}

#
# Setup SSL keys.
# NOTE: This is only for the development purposes.
#       Please never use these keys for production.
#
function setup_ssl () {
    cd $MY_HME
    SSL_DIR="$(pwd)/sugar/etc/sugar/ssl"
    mkdir $SSL_DIR
    openssl req -newkey rsa:2048 -nodes -keyout $SSL_DIR/key.pem -x509 -days 365 -out $SSL_DIR/cert.pem
    openssl x509 -text -noout -in $SSL_DIR/cert.pem
    openssl pkcs12 -inkey $SSL_DIR/key.pem -in $SSL_DIR/cert.pem -export -out $SSL_DIR/certificate.p12
    openssl pkcs12 -in $SSL_DIR/certificate.p12 -noout -info
}

#
# Setup hacking environment for daily use
#
function setup_hacking_env () {
    cd $MY_HME
    echo "PATH=\"$(pwd)/sugar/bin:\$PATH\"" >> "$(pwd)/sugar/dev/hacking"
    echo "source $(pwd)/sugar-env/bin/activate" >> "$(pwd)/sugar/dev/hacking"
}

#
# Say final notes
#
function final_notes () {
    echo
    echo "----[ ALL DONE ]---------------------------------------"
    echo
    echo "Now the last step (and repeat it every time you open"
    echo "this terminal:"
    echo
    echo "    source $(pwd)/sugar/dev/hacking"
    echo
    echo "-------------------------------------------------------"
    echo
    echo "What is next? For example, you could think of this:"
    echo
    echo "    1. git checkout -b your-awesome-feature"
    echo "    2. Fix a bug, write a doc or make something great"
    echo "    3. git push origin your-awesome-feature"
    echo "    4. Make a pull request to the upstream! :-)"
    echo
    echo 'Remember: have a lot of fun!'
    echo
}

echo "Checking requirements"
check_python_version
check_openssl_installed

echo "Cloning Git repo"
checkout_repo

echo "Setting up your virtual environment"
setup_virt_env
setup_ssl
setup_hacking_env
setup_configuration_symlink

final_notes
