# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: Linter
          environment:
            TERM: xterm-256color
          command: |
            . venv/bin/activate
            sugar-lint --disable=R0401 sugar/

      - run:
          name: PEP8 code style checks
          environment:
            TERM: xterm-256color
          command: |
            . venv/bin/activate
            sugar-flake

      - run:
          name: Integration Tests
          command: |
            . venv/bin/activate
            pytest -vv tests/integration

      - run:
          name: Unit Tests
          environment:
            TERM: xterm-256color
          command: |
            . venv/bin/activate
            pytest -vv tests/unit/

      - run:
          name: Module validation
          environment:
            TERM: xterm-256color
          command: |
            . venv/bin/activate
            sugar-valmod -t runner -a

      - run:
          name: Test Coverage Report (info only)
          environment:
            TERM: xterm-256color
          command: |
            . venv/bin/activate
            py.test --cov=sugar tests/
