# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: Linter
          command: |
            . venv/bin/activate
            ./py-lint --disable=R0401 sugar/

      - run:
          name: Unit Tests
          command: |
            . venv/bin/activate
            pytest tests/unit/

      - run:
          name: Test Coverage Report (info only)
          command: |
            . venv/bin/activate
            py.test --cov=sugar tests/

      #- store_artifacts:
      #    path: test-reports
      #    destination: test-reports
